"""init schema

Revision ID: cd4f7e14eb19
Revises: b36bbd7ffdb5
Create Date: 2025-11-05 13:05:09.570153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd4f7e14eb19'
down_revision: Union[str, None] = 'b36bbd7ffdb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_table('notify_templates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('deeplink', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notify_templates_id'), 'notify_templates', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uid')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('group_users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('LEADER', 'MEMBER', name='group_user_roles'), nullable=False),
    sa.Column('status', sa.Enum('REQUEST', 'ACCEPTED', 'REJECTED', name='group_user_status'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_users_group_id'), 'group_users', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_users_id'), 'group_users', ['id'], unique=False)
    op.create_index(op.f('ix_group_users_user_id'), 'group_users', ['user_id'], unique=False)
    op.create_table('halls',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_halls_id'), 'halls', ['id'], unique=False)
    op.create_table('notices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_fix', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notices_group_id'), 'notices', ['group_id'], unique=False)
    op.create_index(op.f('ix_notices_id'), 'notices', ['id'], unique=False)
    op.create_table('notify_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notify_tokens_id'), 'notify_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_notify_tokens_user_id'), 'notify_tokens', ['user_id'], unique=False)
    op.create_table('notify_topics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.Column('user_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notify_topics_group_id'), 'notify_topics', ['group_id'], unique=False)
    op.create_index(op.f('ix_notify_topics_id'), 'notify_topics', ['id'], unique=False)
    op.create_index(op.f('ix_notify_topics_user_id'), 'notify_topics', ['user_id'], unique=False)
    op.create_table('off_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_off_requests_group_id'), 'off_requests', ['group_id'], unique=False)
    op.create_index(op.f('ix_off_requests_id'), 'off_requests', ['id'], unique=False)
    op.create_index(op.f('ix_off_requests_user_id'), 'off_requests', ['user_id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_group_id'), 'schedules', ['group_id'], unique=False)
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    op.create_index(op.f('ix_schedules_user_id'), 'schedules', ['user_id'], unique=False)
    op.create_table('hall_positions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('hall_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['hall_id'], ['halls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hall_positions_id'), 'hall_positions', ['id'], unique=False)
    op.create_table('notice_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('notice_id', sa.BigInteger(), nullable=False),
    sa.Column('s3_bucket', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notice_files_id'), 'notice_files', ['id'], unique=False)
    op.create_table('notice_images',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('notice_id', sa.BigInteger(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('s3_bucket', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notice_images_id'), 'notice_images', ['id'], unique=False)
    op.create_table('notice_reads',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('notice_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notice_reads_id'), 'notice_reads', ['id'], unique=False)
    op.create_index(op.f('ix_notice_reads_notice_id'), 'notice_reads', ['notice_id'], unique=False)
    op.create_index(op.f('ix_notice_reads_user_id'), 'notice_reads', ['user_id'], unique=False)
    op.create_table('notify_histories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('notice_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=True),
    sa.Column('deeplink', sa.String(length=255), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notify_histories_id'), 'notify_histories', ['id'], unique=False)
    op.create_table('performances',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('hall_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['hall_id'], ['halls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performances_group_id'), 'performances', ['group_id'], unique=False)
    op.create_index(op.f('ix_performances_hall_id'), 'performances', ['hall_id'], unique=False)
    op.create_index(op.f('ix_performances_id'), 'performances', ['id'], unique=False)
    op.create_table('schedule_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('replacement_member_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('request_type', sa.Enum('OFF', 'ABSENCE', 'REPLACEMENT', name='schedule_request_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('REQUEST', 'ACCEPTED', 'REJECTED', name='schedule_request_status_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['replacement_member_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_requests_id'), 'schedule_requests', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_requests_schedule_id'), 'schedule_requests', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_schedule_requests_user_id'), 'schedule_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_requests_user_id'), table_name='schedule_requests')
    op.drop_index(op.f('ix_schedule_requests_schedule_id'), table_name='schedule_requests')
    op.drop_index(op.f('ix_schedule_requests_id'), table_name='schedule_requests')
    op.drop_table('schedule_requests')
    op.drop_index(op.f('ix_performances_id'), table_name='performances')
    op.drop_index(op.f('ix_performances_hall_id'), table_name='performances')
    op.drop_index(op.f('ix_performances_group_id'), table_name='performances')
    op.drop_table('performances')
    op.drop_index(op.f('ix_notify_histories_id'), table_name='notify_histories')
    op.drop_table('notify_histories')
    op.drop_index(op.f('ix_notice_reads_user_id'), table_name='notice_reads')
    op.drop_index(op.f('ix_notice_reads_notice_id'), table_name='notice_reads')
    op.drop_index(op.f('ix_notice_reads_id'), table_name='notice_reads')
    op.drop_table('notice_reads')
    op.drop_index(op.f('ix_notice_images_id'), table_name='notice_images')
    op.drop_table('notice_images')
    op.drop_index(op.f('ix_notice_files_id'), table_name='notice_files')
    op.drop_table('notice_files')
    op.drop_index(op.f('ix_hall_positions_id'), table_name='hall_positions')
    op.drop_table('hall_positions')
    op.drop_index(op.f('ix_schedules_user_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_group_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_off_requests_user_id'), table_name='off_requests')
    op.drop_index(op.f('ix_off_requests_id'), table_name='off_requests')
    op.drop_index(op.f('ix_off_requests_group_id'), table_name='off_requests')
    op.drop_table('off_requests')
    op.drop_index(op.f('ix_notify_topics_user_id'), table_name='notify_topics')
    op.drop_index(op.f('ix_notify_topics_id'), table_name='notify_topics')
    op.drop_index(op.f('ix_notify_topics_group_id'), table_name='notify_topics')
    op.drop_table('notify_topics')
    op.drop_index(op.f('ix_notify_tokens_user_id'), table_name='notify_tokens')
    op.drop_index(op.f('ix_notify_tokens_id'), table_name='notify_tokens')
    op.drop_table('notify_tokens')
    op.drop_index(op.f('ix_notices_id'), table_name='notices')
    op.drop_index(op.f('ix_notices_group_id'), table_name='notices')
    op.drop_table('notices')
    op.drop_index(op.f('ix_halls_id'), table_name='halls')
    op.drop_table('halls')
    op.drop_index(op.f('ix_group_users_user_id'), table_name='group_users')
    op.drop_index(op.f('ix_group_users_id'), table_name='group_users')
    op.drop_index(op.f('ix_group_users_group_id'), table_name='group_users')
    op.drop_table('group_users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_notify_templates_id'), table_name='notify_templates')
    op.drop_table('notify_templates')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
